
services:
  reverse-proxy:
    image: openresty/openresty:alpine    
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports: 
      - 8443:443
      - 8080:80
   